name: container
on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']

jobs:
  build-and-push:
    name: Build and conditionally push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: wasp-agent
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile

    - name: Push To quay.io
      if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/fdeutsch/wstunnel
        username: fdeutsch+bot
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
