name: lint

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']

jobs:
  bash:
    name: Lint bash scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: bash -n contrib/*.sh
